// lib/survey/questions.ts
// Complete survey definition for the Cubet Music Experience Study

export interface QuestionOption {
  value: string;
  label: string;
}

export type QuestionType =
  | 'single'       // Single-choice (radio)
  | 'multi'        // Multi-select (checkboxes)
  | 'textarea'     // Free text only
  | 'rating';      // 1-5 rating

export interface SurveyQuestion {
  id: string;
  section: number;
  sectionTitle: string;
  questionNumber: number;
  text: string;
  type: QuestionType;
  options?: QuestionOption[];
  maxSelect?: number;         // For multi: maximum selections
  required: boolean;
  optionalText?: string;     // Prompt for optional textarea
  textareaPlaceholder?: string;
  // Branching: show optional textarea only when these values are selected
  showTextareaWhen?: string[];
}

export const SECTIONS = [
  { id: 1, title: 'Your Relationship with Music' },
  { id: 2, title: 'When and Why You Listen' },
  { id: 3, title: 'Music Discovery' },
  { id: 4, title: 'Existing Music Platforms' },
  { id: 5, title: 'What Music Means to You' },
  { id: 6, title: 'Personalization' },
  { id: 7, title: 'The Big Question' },
  { id: 8, title: 'Future Experience' },
];

export const SURVEY_QUESTIONS: SurveyQuestion[] = [
  // ─── SECTION 1 ────────────────────────────────────────────────────────────
  {
    id: 'q1',
    section: 1,
    sectionTitle: 'Your Relationship with Music',
    questionNumber: 1,
    text: 'How important is music in your everyday life?',
    type: 'single',
    required: true,
    options: [
      { value: 'just_listening', label: 'Just something I listen to' },
      { value: 'somewhat_important', label: 'Somewhat important' },
      { value: 'very_important', label: 'Very important' },
      { value: 'major_part', label: 'A major part of my life' },
      { value: 'part_of_who_i_am', label: 'Music is a part of who I am' },
    ],
    optionalText: 'Want to tell us why?',
  },
  {
    id: 'q2',
    section: 1,
    sectionTitle: 'Your Relationship with Music',
    questionNumber: 2,
    text: 'How much music do you usually listen to in a day?',
    type: 'single',
    required: true,
    options: [
      { value: 'less_30min', label: 'Less than 30 minutes' },
      { value: '30min_1hr', label: '30 minutes – 1 hour' },
      { value: '1_2hr', label: '1–2 hours' },
      { value: '2_4hr', label: '2–4 hours' },
      { value: '4hr_plus', label: '4+ hours' },
      { value: 'varies', label: 'It varies a lot' },
    ],
  },
  {
    id: 'q3',
    section: 1,
    sectionTitle: 'Your Relationship with Music',
    questionNumber: 3,
    text: 'Which describes you as a listener?',
    type: 'multi',
    maxSelect: 3,
    required: true,
    options: [
      { value: 'familiar_songs', label: 'I mostly listen to songs I already know' },
      { value: 'love_discovery', label: 'I love discovering new music' },
      { value: 'mood_based', label: 'I listen according to my mood' },
      { value: 'activity_based', label: 'I listen according to what I\'m doing' },
      { value: 'follow_artists', label: 'I follow specific artists' },
      { value: 'create_playlists', label: 'I create playlists' },
      { value: 'albums', label: 'I mainly listen to albums' },
      { value: 'many_genres', label: 'I jump between lots of genres' },
      { value: 'few_genres', label: 'I usually stick to a few genres' },
      { value: 'background', label: 'I use music mostly as background' },
      { value: 'active_search', label: 'I actively search for music' },
    ],
  },

  // ─── SECTION 2 ────────────────────────────────────────────────────────────
  {
    id: 'q4',
    section: 2,
    sectionTitle: 'When and Why You Listen',
    questionNumber: 4,
    text: 'When do you usually listen to music?',
    type: 'multi',
    required: true,
    options: [
      { value: 'studying', label: 'Studying' },
      { value: 'working', label: 'Working' },
      { value: 'travelling', label: 'Travelling' },
      { value: 'commuting', label: 'Commuting' },
      { value: 'exercising', label: 'Exercising' },
      { value: 'relaxing', label: 'Relaxing' },
      { value: 'gaming', label: 'Gaming' },
      { value: 'socializing', label: 'Socializing' },
      { value: 'parties', label: 'Parties' },
      { value: 'eating_cooking', label: 'Eating / cooking' },
      { value: 'before_sleeping', label: 'Before sleeping' },
      { value: 'when_alone', label: 'When I\'m alone' },
      { value: 'almost_always', label: 'Almost all the time' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q5',
    section: 2,
    sectionTitle: 'When and Why You Listen',
    questionNumber: 5,
    text: 'What usually determines what you listen to?',
    type: 'multi',
    maxSelect: 5,
    required: true,
    options: [
      { value: 'mood', label: 'My mood' },
      { value: 'activity', label: 'My activity' },
      { value: 'energy_level', label: 'Energy level' },
      { value: 'genre', label: 'Genre' },
      { value: 'artist', label: 'Artist' },
      { value: 'lyrics', label: 'Lyrics' },
      { value: 'language', label: 'Language' },
      { value: 'familiarity', label: 'Familiarity' },
      { value: 'discovering_new', label: 'Discovering something new' },
      { value: 'time_of_day', label: 'Time of day' },
      { value: 'memories', label: 'Memories' },
      { value: 'recommendations', label: 'Recommendations' },
      { value: 'recently_listening', label: 'What I\'ve recently been listening to' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q6',
    section: 2,
    sectionTitle: 'When and Why You Listen',
    questionNumber: 6,
    text: 'What are your main reasons for listening to music?',
    type: 'multi',
    maxSelect: 5,
    required: true,
    options: [
      { value: 'relax', label: 'Relax' },
      { value: 'improve_mood', label: 'Improve my mood' },
      { value: 'maintain_mood', label: 'Maintain my current mood' },
      { value: 'focus', label: 'Focus' },
      { value: 'study', label: 'Study' },
      { value: 'get_energized', label: 'Get energized' },
      { value: 'feel_motivated', label: 'Feel motivated' },
      { value: 'escape', label: 'Escape from everything' },
      { value: 'remember_moments', label: 'Remember people or moments' },
      { value: 'express_myself', label: 'Express myself' },
      { value: 'feel_connected', label: 'Feel connected' },
      { value: 'discover_new', label: 'Discover something new' },
      { value: 'entertainment', label: 'Entertainment' },
      { value: 'habit', label: 'Habit' },
      { value: 'other', label: 'Other' },
    ],
    optionalText: 'Is there another reason you listen to music that isn\'t listed above?',
  },

  // ─── SECTION 3 ────────────────────────────────────────────────────────────
  {
    id: 'q7',
    section: 3,
    sectionTitle: 'Music Discovery',
    questionNumber: 7,
    text: 'Where do you usually discover new music?',
    type: 'multi',
    required: true,
    options: [
      { value: 'spotify', label: 'Spotify' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'youtube_music', label: 'YouTube Music' },
      { value: 'apple_music', label: 'Apple Music' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'tiktok', label: 'TikTok' },
      { value: 'friends', label: 'Friends' },
      { value: 'family', label: 'Family' },
      { value: 'playlists', label: 'Playlists' },
      { value: 'artists', label: 'Artists' },
      { value: 'movies_tv', label: 'Movies / TV' },
      { value: 'games', label: 'Games' },
      { value: 'radio', label: 'Radio' },
      { value: 'concerts', label: 'Concerts' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q8',
    section: 3,
    sectionTitle: 'Music Discovery',
    questionNumber: 8,
    text: 'What makes you give a new song a chance?',
    type: 'multi',
    maxSelect: 4,
    required: true,
    options: [
      { value: 'know_artist', label: 'I already like the artist' },
      { value: 'recommended', label: 'Someone recommended it' },
      { value: 'first_seconds', label: 'The first few seconds sound good' },
      { value: 'mood_vibe', label: 'The mood / vibe' },
      { value: 'lyrics', label: 'Lyrics' },
      { value: 'genre', label: 'Genre' },
      { value: 'popularity', label: 'The artist\'s popularity' },
      { value: 'social_media', label: 'Social media' },
      { value: 'artwork', label: 'Album artwork' },
      { value: 'song_title', label: 'Song title' },
      { value: 'curiosity', label: 'Curiosity' },
      { value: 'random', label: 'I randomly came across it' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q9',
    section: 3,
    sectionTitle: 'Music Discovery',
    questionNumber: 9,
    text: 'How often do you discover a song you genuinely love?',
    type: 'single',
    required: true,
    options: [
      { value: 'very_often', label: 'Very often' },
      { value: 'often', label: 'Often' },
      { value: 'sometimes', label: 'Sometimes' },
      { value: 'rarely', label: 'Rarely' },
      { value: 'almost_never', label: 'Almost never' },
    ],
  },
  {
    id: 'q10',
    section: 3,
    sectionTitle: 'Music Discovery',
    questionNumber: 10,
    text: 'When a recommendation is bad, what usually makes it bad?',
    type: 'multi',
    required: true,
    options: [
      { value: 'wrong_mood', label: "It doesn't match my mood" },
      { value: 'wrong_activity', label: "It doesn't match what I'm doing" },
      { value: 'wrong_genre', label: 'Wrong genre' },
      { value: 'too_repetitive', label: 'Too repetitive' },
      { value: 'too_familiar', label: 'Too many songs I already know' },
      { value: 'too_unfamiliar', label: "Too many songs I don't know" },
      { value: 'recent_bias', label: "Too influenced by something I listened to recently" },
      { value: 'popular_not_personal', label: "It recommends popular songs instead of songs I'd actually like" },
      { value: 'similar_artist_different_feel', label: 'Similar artist, but completely different feeling' },
      { value: 'doesnt_understand_taste', label: "It doesn't understand my taste" },
      { value: 'not_enough_variety', label: 'Not enough variety' },
      { value: 'too_random', label: 'Too much randomness' },
      { value: 'other', label: 'Other' },
    ],
  },

  // ─── SECTION 4 ────────────────────────────────────────────────────────────
  {
    id: 'q11',
    section: 4,
    sectionTitle: 'Existing Music Platforms',
    questionNumber: 11,
    text: 'Which music platforms do you currently use?',
    type: 'multi',
    required: true,
    options: [
      { value: 'spotify', label: 'Spotify' },
      { value: 'youtube_music', label: 'YouTube Music' },
      { value: 'apple_music', label: 'Apple Music' },
      { value: 'soundcloud', label: 'SoundCloud' },
      { value: 'jiosaavn', label: 'JioSaavn' },
      { value: 'amazon_music', label: 'Amazon Music' },
      { value: 'gaana', label: 'Gaana' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q12',
    section: 4,
    sectionTitle: 'Existing Music Platforms',
    questionNumber: 12,
    text: 'What do you like most about your current music platform?',
    type: 'multi',
    maxSelect: 3,
    required: true,
    options: [
      { value: 'library', label: 'Music library' },
      { value: 'recommendations', label: 'Recommendations' },
      { value: 'playlists', label: 'Playlists' },
      { value: 'discovery', label: 'Discovering new artists' },
      { value: 'ui', label: 'User interface' },
      { value: 'audio_quality', label: 'Audio quality' },
      { value: 'personalization', label: 'Personalization' },
      { value: 'lyrics', label: 'Lyrics' },
      { value: 'social', label: 'Social features' },
      { value: 'ease_of_use', label: 'Ease of use' },
      { value: 'convenience', label: 'Convenience' },
      { value: 'nothing', label: 'Nothing in particular' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q13',
    section: 4,
    sectionTitle: 'Existing Music Platforms',
    questionNumber: 13,
    text: 'What is the biggest problem you have with current music platforms?',
    type: 'multi',
    maxSelect: 3,
    required: true,
    options: [
      { value: 'inaccurate_recs', label: "Recommendations aren't accurate" },
      { value: 'repetitive_recs', label: 'Recommendations become repetitive' },
      { value: 'too_much_effort', label: 'Too much effort to find the right music' },
      { value: 'cant_find_mood', label: "I can't easily find music for my current mood" },
      { value: 'cant_find_activity', label: "I can't easily find music for an activity" },
      { value: 'hard_to_discover', label: 'Discovering genuinely new music is difficult' },
      { value: 'irrelevant_recs', label: 'Too many irrelevant recommendations' },
      { value: 'doesnt_understand', label: "The platform doesn't understand my taste" },
      { value: 'too_many_features', label: 'Too many features / clutter' },
      { value: 'not_enough_control', label: 'Not enough control' },
      { value: 'not_enough_personal', label: 'Not enough personalization' },
      { value: 'nothing_major', label: 'Nothing major bothers me' },
      { value: 'other', label: 'Other' },
    ],
    optionalText: "Tell us about a frustrating experience you've had with a music app.",
  },

  // ─── SECTION 5 ────────────────────────────────────────────────────────────
  {
    id: 'q14',
    section: 5,
    sectionTitle: 'What Music Means to You',
    questionNumber: 14,
    text: 'What does music help you do?',
    type: 'multi',
    maxSelect: 5,
    required: true,
    options: [
      { value: 'change_mood', label: 'Change my mood' },
      { value: 'understand_feelings', label: 'Understand my feelings' },
      { value: 'concentrate', label: 'Concentrate' },
      { value: 'relax', label: 'Relax' },
      { value: 'feel_energetic', label: 'Feel energetic' },
      { value: 'feel_nostalgic', label: 'Feel nostalgic' },
      { value: 'escape', label: 'Escape' },
      { value: 'connect', label: 'Connect with people' },
      { value: 'express_personality', label: 'Express my personality' },
      { value: 'create_memories', label: 'Create memories' },
      { value: 'relive_memories', label: 'Relive memories' },
      { value: 'feel_less_alone', label: 'Feel less alone' },
      { value: 'pass_time', label: 'Pass time' },
      { value: 'discover_myself', label: 'Discover myself' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q15',
    section: 5,
    sectionTitle: 'What Music Means to You',
    questionNumber: 15,
    text: 'What do you value most in a song?',
    type: 'multi',
    maxSelect: 4,
    required: true,
    options: [
      { value: 'emotion', label: 'Emotion' },
      { value: 'lyrics', label: 'Lyrics' },
      { value: 'melody', label: 'Melody' },
      { value: 'beat', label: 'Beat' },
      { value: 'voice', label: 'Voice' },
      { value: 'production', label: 'Production' },
      { value: 'energy', label: 'Energy' },
      { value: 'atmosphere', label: 'Atmosphere' },
      { value: 'nostalgia', label: 'Nostalgia' },
      { value: 'originality', label: 'Originality' },
      { value: 'relatability', label: 'Relatability' },
      { value: 'memories', label: 'The memories attached to it' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q16',
    section: 5,
    sectionTitle: 'What Music Means to You',
    questionNumber: 16,
    text: 'Has music ever become strongly connected to a person, place, or memory?',
    type: 'single',
    required: true,
    options: [
      { value: 'yes_very_often', label: 'Yes, very often' },
      { value: 'yes_sometimes', label: 'Yes, sometimes' },
      { value: 'rarely', label: 'Rarely' },
      { value: 'no', label: 'No' },
    ],
    optionalText: "Tell us about it, if you'd like.",
    showTextareaWhen: ['yes_very_often', 'yes_sometimes'],
  },

  // ─── SECTION 6 ────────────────────────────────────────────────────────────
  {
    id: 'q17',
    section: 6,
    sectionTitle: 'Personalization',
    questionNumber: 17,
    text: 'What should a music app understand about you?',
    type: 'multi',
    maxSelect: 6,
    required: true,
    options: [
      { value: 'fav_artists', label: 'My favorite artists' },
      { value: 'fav_genres', label: 'My favorite genres' },
      { value: 'current_mood', label: 'My current mood' },
      { value: 'usual_moods', label: 'My usual moods' },
      { value: 'activity', label: "What I'm doing" },
      { value: 'time_of_day', label: 'Time of day' },
      { value: 'energy_level', label: 'My energy level' },
      { value: 'language_pref', label: 'Languages I prefer' },
      { value: 'recent_listening', label: "Music I've been listening to recently" },
      { value: 'want_more_of', label: 'Music I want more of' },
      { value: 'tired_of', label: 'Music I am tired of' },
      { value: 'openness', label: 'My openness to discovering new music' },
      { value: 'musical_memories', label: 'My musical memories' },
      { value: 'changing_taste', label: 'My changing taste' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q18',
    section: 6,
    sectionTitle: 'Personalization',
    questionNumber: 18,
    text: 'How much control do you want over recommendations?',
    type: 'single',
    required: true,
    options: [
      { value: 'just_give_me', label: 'Just give me something good' },
      { value: 'mostly_recommend', label: 'Mostly recommend for me' },
      { value: 'some_control', label: 'Give me some control' },
      { value: 'describe_exactly', label: 'Let me describe exactly what I want' },
      { value: 'full_control', label: 'I want full control' },
    ],
  },
  {
    id: 'q19',
    section: 6,
    sectionTitle: 'Personalization',
    questionNumber: 19,
    text: 'Which experience sounds most appealing?',
    type: 'single',
    required: true,
    options: [
      { value: 'familiar', label: "Give me music I already know I'll enjoy" },
      { value: 'surprise', label: 'Surprise me with something completely new' },
      { value: 'mood_match', label: 'Give me music that matches my current mood' },
      { value: 'activity_match', label: "Give me music that matches what I'm doing" },
      { value: 'balance', label: 'Give me a balance of familiar + new' },
      { value: 'describe_and_find', label: 'Let me describe what I want and figure it out for me' },
    ],
  },

  // ─── SECTION 7 ────────────────────────────────────────────────────────────
  {
    id: 'q20',
    section: 7,
    sectionTitle: 'The Big Question',
    questionNumber: 20,
    text: "What do you think today's music apps still don't understand about you?",
    type: 'textarea',
    required: false,
    textareaPlaceholder: "They know what I listen to, but they don't understand...",
  },

  // ─── SECTION 8 ────────────────────────────────────────────────────────────
  {
    id: 'q21',
    section: 8,
    sectionTitle: 'Future Experience',
    questionNumber: 21,
    text: 'What would make you genuinely excited to use a new music experience?',
    type: 'multi',
    maxSelect: 3,
    required: true,
    options: [
      { value: 'better_recs', label: 'Better recommendations' },
      { value: 'better_mood', label: 'Better mood matching' },
      { value: 'better_discovery', label: 'Better discovery' },
      { value: 'more_personal', label: 'More personalization' },
      { value: 'more_control', label: 'More control' },
      { value: 'less_effort', label: 'Less effort' },
      { value: 'better_playlists', label: 'Better playlists' },
      { value: 'understand_habits', label: 'Understanding my listening habits' },
      { value: 'different', label: 'Something completely different' },
      { value: 'other', label: 'Other' },
    ],
    optionalText: 'Want to explain your answer?',
  },
  {
    id: 'q22',
    section: 8,
    sectionTitle: 'Future Experience',
    questionNumber: 22,
    text: 'Would you be interested in trying a new music experience based on what you\'ve told us?',
    type: 'single',
    required: true,
    options: [
      { value: 'definitely', label: 'Definitely' },
      { value: 'probably', label: 'Probably' },
      { value: 'maybe', label: 'Maybe' },
      { value: 'probably_not', label: 'Probably not' },
      { value: 'no', label: 'No' },
    ],
    optionalText: 'What would make you try it?',
  },
  {
    id: 'q23',
    section: 8,
    sectionTitle: 'Future Experience',
    questionNumber: 23,
    text: 'Interested in participating in future user testing or feedback sessions?',
    type: 'single',
    required: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
    ],
  },
];

export const TOTAL_QUESTIONS = SURVEY_QUESTIONS.length;

export function getQuestionById(id: string): SurveyQuestion | undefined {
  return SURVEY_QUESTIONS.find((q) => q.id === id);
}

export function getQuestionsBySection(sectionId: number): SurveyQuestion[] {
  return SURVEY_QUESTIONS.filter((q) => q.section === sectionId);
}
