// lib/admin/mockData.ts
// Realistic sample dataset for demonstration and local exploration of the Cubet Music Study

import { AdminResponseItem } from './types';

export const MOCK_RESPONSES: AdminResponseItem[] = [
  {
    id: 'res_01j8m49a9b1c2d3e4f5a6b7c8d',
    name: 'Elena Rostova',
    email: 'elena.rostova@designlab.io',
    age_range: '25-34',
    submitted_at: '2026-09-27T08:14:22Z',
    completion_time_seconds: 284,
    future_research_opt_in: true,
    survey_version: '1.0',
    answers: {
      q1: { selected: 'part_of_who_i_am', text: 'Music grounds my entire workday and creative flow.' },
      q2: { selected: '4hr_plus' },
      q3: { selected: ['love_discovery', 'mood_based', 'create_playlists'] },
      q4: { selected: ['working', 'relaxing', 'when_alone'] },
      q5: { selected: ['mood', 'energy_level', 'lyrics'] },
      q6: { selected: ['focus', 'improve_mood', 'discover_new'], text: 'A tool for emotional regulation when context switching.' },
      q7: { selected: ['spotify', 'playlists', 'friends', 'instagram'] },
      q8: { selected: ['first_seconds', 'mood_vibe', 'curiosity'] },
      q9: { selected: ['often'] },
      q10: { selected: ['wrong_mood', 'too_repetitive', 'popular_not_personal'] },
      q11: { selected: ['spotify', 'apple_music'] },
      q12: { selected: ['playlists', 'ui', 'ease_of_use'] },
      q13: { selected: ['repetitive_recs', 'inaccurate_recs', 'cant_find_mood'], text: 'Daily Mixes recycle the same 12 tracks I played 3 weeks ago.' },
      q14: { selected: ['concentrate', 'change_mood', 'escape'] },
      q15: { selected: ['emotion', 'atmosphere', 'production'] },
      q16: { selected: 'yes_very_often', text: 'Hearing ambient synth takes me right back to rainy evenings in Berlin.' },
      q17: { selected: ['current_mood', 'energy_level', 'changing_taste', 'want_more_of'] },
      q18: { selected: 'describe_exactly' },
      q19: { selected: 'describe_and_find' },
      q20: { text: "Current algorithms treat taste as a static cluster of genres. They don't understand that at 9am I need ambient without drums, but by 3pm I want polyrhythmic electronic." },
      q21: { selected: ['better_mood', 'better_discovery', 'more_control'], text: 'A dynamic interface that responds to how I describe my mental state.' },
      q22: { selected: 'definitely', text: 'If it truly avoids algorithmic echo chambers, count me in.' },
      q23: { selected: 'yes' },
    },
  },
  {
    id: 'res_02k9n50b0c2d3e4f5a6b7c8d9e',
    name: 'Marcus Chen',
    email: 'marcus.chen@soundfrontier.org',
    age_range: '18-24',
    submitted_at: '2026-09-27T07:45:10Z',
    completion_time_seconds: 320,
    future_research_opt_in: true,
    survey_version: '1.0',
    answers: {
      q1: { selected: 'major_part' },
      q2: { selected: '2_4hr' },
      q3: { selected: ['love_discovery', 'active_search', 'many_genres'] },
      q4: { selected: ['studying', 'commuting', 'gaming'] },
      q5: { selected: ['energy_level', 'activity', 'genre'] },
      q6: { selected: ['study', 'get_energized', 'entertainment'] },
      q7: { selected: ['youtube', 'soundcloud', 'tiktok'] },
      q8: { selected: ['first_seconds', 'social_media', 'artwork'] },
      q9: { selected: ['very_often'] },
      q10: { selected: ['popular_not_personal', 'doesnt_understand_taste', 'too_familiar'] },
      q11: { selected: ['youtube_music', 'soundcloud'] },
      q12: { selected: ['discovery', 'library'] },
      q13: { selected: ['hard_to_discover', 'repetitive_recs'], text: 'Mainstream hits get pushed into my feed no matter how many underground producers I follow.' },
      q14: { selected: ['concentrate', 'feel_energetic', 'pass_time'] },
      q15: { selected: ['beat', 'production', 'originality'] },
      q16: { selected: 'yes_sometimes', text: 'Certain lo-fi tracks remind me of late-night finals week.' },
      q17: { selected: ['openness', 'tired_of', 'fav_genres', 'activity'] },
      q18: { selected: 'full_control' },
      q19: { selected: 'surprise' },
      q20: { text: "They assume because I listened to one video game soundtrack once, my entire account is now a soundtrack feed for 3 months." },
      q21: { selected: ['better_discovery', 'different', 'less_effort'] },
      q22: { selected: 'definitely' },
      q23: { selected: 'yes' },
    },
  },
  {
    id: 'res_03l0o61c1d3e4f5a6b7c8d9e0f',
    name: 'Sarah Lindqvist',
    email: 'sarah.lindqvist@nordicaudio.se',
    age_range: '35-44',
    submitted_at: '2026-09-27T06:30:19Z',
    completion_time_seconds: 412,
    future_research_opt_in: true,
    survey_version: '1.0',
    answers: {
      q1: { selected: 'part_of_who_i_am', text: 'I grew up playing piano and cello; sound texture is vital to my well-being.' },
      q2: { selected: '2_4hr' },
      q3: { selected: ['albums', 'familiar_songs', 'follow_artists'] },
      q4: { selected: ['relaxing', 'eating_cooking', 'when_alone'] },
      q5: { selected: ['artist', 'memories', 'mood'] },
      q6: { selected: ['relax', 'remember_moments', 'feel_connected'] },
      q7: { selected: ['radio', 'concerts', 'friends'] },
      q8: { selected: ['know_artist', 'recommended', 'lyrics'] },
      q9: { selected: ['sometimes'] },
      q10: { selected: ['doesnt_understand_taste', 'wrong_genre', 'similar_artist_different_feel'] },
      q11: { selected: ['apple_music', 'spotify'] },
      q12: { selected: ['audio_quality', 'library'] },
      q13: { selected: ['too_many_features', 'not_enough_control'], text: 'The apps are cluttered with podcasts, video feeds, and social nonsense when all I want is pristine listening.' },
      q14: { selected: ['relax', 'relive_memories', 'understand_feelings'] },
      q15: { selected: ['emotion', 'melody', 'lyrics', 'production'] },
      q16: { selected: 'yes_very_often', text: 'Nils Frahm takes me to autumn in Stockholm.' },
      q17: { selected: ['fav_artists', 'musical_memories', 'current_mood'] },
      q18: { selected: 'mostly_recommend' },
      q19: { selected: 'balance' },
      q20: { text: "They confuse fast engagement with deep satisfaction. I don't want a 15-second TikTok clip of an audio track; I want an immersive experience." },
      q21: { selected: ['more_personal', 'better_recs', 'different'] },
      q22: { selected: 'probably' },
      q23: { selected: 'yes' },
    },
  },
  {
    id: 'res_04m1p72d2e4f5a6b7c8d9e0f1g',
    name: 'Devin Thorne',
    email: 'devin.thorne@vibeengine.co',
    age_range: '25-34',
    submitted_at: '2026-09-26T21:12:00Z',
    completion_time_seconds: 195,
    future_research_opt_in: false,
    survey_version: '1.0',
    answers: {
      q1: { selected: 'very_important' },
      q2: { selected: '1_2hr' },
      q3: { selected: ['activity_based', 'background'] },
      q4: { selected: ['exercising', 'commuting'] },
      q5: { selected: ['energy_level', 'activity'] },
      q6: { selected: ['get_energized', 'feel_motivated'] },
      q7: { selected: ['spotify', 'playlists'] },
      q8: { selected: ['first_seconds', 'mood_vibe'] },
      q9: { selected: ['sometimes'] },
      q10: { selected: ['wrong_mood', 'wrong_activity'] },
      q11: { selected: ['spotify'] },
      q12: { selected: ['convenience', 'ease_of_use'] },
      q13: { selected: ['cant_find_activity', 'too_much_effort'] },
      q14: { selected: ['feel_energetic', 'concentrate'] },
      q15: { selected: ['beat', 'energy'] },
      q16: { selected: 'yes_sometimes' },
      q17: { selected: ['activity', 'energy_level'] },
      q18: { selected: 'just_give_me' },
      q19: { selected: 'activity_match' },
      q20: { text: 'Running cadence matching is still terrible across the board.' },
      q21: { selected: ['better_mood', 'less_effort'] },
      q22: { selected: 'probably' },
      q23: { selected: 'no' },
    },
  },
  {
    id: 'res_05n2q83e3f5a6b7c8d9e0f1g2h',
    name: 'Amina Al-Mansoor',
    email: 'amina.mansoor@acoustics.ae',
    age_range: '18-24',
    submitted_at: '2026-09-26T18:04:45Z',
    completion_time_seconds: 350,
    future_research_opt_in: true,
    survey_version: '1.0',
    answers: {
      q1: { selected: 'part_of_who_i_am' },
      q2: { selected: '4hr_plus' },
      q3: { selected: ['love_discovery', 'many_genres', 'active_search'] },
      q4: { selected: ['studying', 'working', 'almost_always'] },
      q5: { selected: ['mood', 'discovering_new', 'language'] },
      q6: { selected: ['focus', 'discover_new', 'express_myself'] },
      q7: { selected: ['youtube', 'spotify', 'instagram', 'friends'] },
      q8: { selected: ['mood_vibe', 'curiosity', 'first_seconds'] },
      q9: { selected: ['often'] },
      q10: { selected: ['doesnt_understand_taste', 'not_enough_variety'] },
      q11: { selected: ['spotify', 'youtube_music'] },
      q12: { selected: ['library', 'discovery'] },
      q13: { selected: ['hard_to_discover', 'doesnt_understand'], text: 'Non-western music recommendation is atrocious; it bundles entire continents into one generic playlist.' },
      q14: { selected: ['change_mood', 'discover_myself', 'create_memories'] },
      q15: { selected: ['emotion', 'lyrics', 'originality'] },
      q16: { selected: 'yes_very_often', text: 'Oud melodies and traditional percussion tied to family gatherings.' },
      q17: { selected: ['language_pref', 'openness', 'changing_taste', 'current_mood'] },
      q18: { selected: 'describe_exactly' },
      q19: { selected: 'describe_and_find' },
      q20: { text: "Cross-cultural and bilingual music tastes are completely broken. If I listen to indie Arabic folk, don't suddenly fill my feed with Bollywood pop." },
      q21: { selected: ['better_discovery', 'more_personal', 'understand_habits'] },
      q22: { selected: 'definitely', text: 'Need a team that actually respects global nuances.' },
      q23: { selected: 'yes' },
    },
  },
  {
    id: 'res_06o3r94f4a6b7c8d9e0f1g2h3i',
    name: 'Julian Vance',
    email: 'julian.vance@sounddesign.net',
    age_range: '45-54',
    submitted_at: '2026-09-26T15:20:12Z',
    completion_time_seconds: 388,
    future_research_opt_in: true,
    survey_version: '1.0',
    answers: {
      q1: { selected: 'major_part' },
      q2: { selected: '1_2hr' },
      q3: { selected: ['albums', 'few_genres', 'follow_artists'] },
      q4: { selected: ['relaxing', 'when_alone'] },
      q5: { selected: ['artist', 'genre', 'memories'] },
      q6: { selected: ['relax', 'remember_moments', 'entertainment'] },
      q7: { selected: ['radio', 'playlists', 'concerts'] },
      q8: { selected: ['know_artist', 'genre', 'recommended'] },
      q9: { selected: ['rarely'] },
      q10: { selected: ['too_random', 'popular_not_personal'] },
      q11: { selected: ['apple_music', 'amazon_music'] },
      q12: { selected: ['audio_quality', 'library'] },
      q13: { selected: ['inaccurate_recs', 'too_many_features'] },
      q14: { selected: ['relax', 'relive_memories'] },
      q15: { selected: ['production', 'voice', 'nostalgia'] },
      q16: { selected: 'yes_very_often' },
      q17: { selected: ['fav_artists', 'fav_genres'] },
      q18: { selected: 'some_control' },
      q19: { selected: 'familiar' },
      q20: { text: 'Stop trying to turn music players into social networking platforms.' },
      q21: { selected: ['more_control', 'better_recs'] },
      q22: { selected: 'maybe' },
      q23: { selected: 'yes' },
    },
  },
];
